name: Detect Project Change

on:
  push:

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Changes
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Commit: ${{ github.sha }}"
      
      - name: Repository Changed
        run: echo "A Project has been updated!"
