name: Build React Project

on: 
  push:
    paths:
      - 'react/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: react

    steps:
      - name: React Checkout
        uses: actions/checkout@v4
      
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'react/package-lock.json'
      
      - name: Install dependencies
        run: npm install

      - name: Build React Project
        run: npm run build

      - name: Push to react-build branch
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: react-build
          folder: react/dist
