name: Build React Project

on: 
  push:
    paths:
      - 'react/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: laravel

    steps:
      - uses: actions/checkout@v4

      - run: pwd

      - run: cat README.md
      
      - run: echo "React Project Built"
